In [ ]:
#ex1
import numpy as np
a = np.array([1, 2, 3])
li = a.tolist()
print(li)

[1, 2, 3]


In [2]:
#ex2
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.trace())


15


In [37]:
#ex3
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
row=len(a)
y=-row
x=5
while y<0:
  z=0
  while len(a[0])>z :
    t=a[y,z]
    if t>x:
      print(t)
    z=z+1
  y=y+1
  

6
7
8
9


In [71]:
#ex4
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,5,7],[3,6,0],[8,4,2]])
c=np.random.random((3,3))
row=len(a)
y=-row
while y<0:
  z=0
  while len(a[0])>z :
    k=a[y,z]
    l=b[y,z]
    q=k+l
    c[y,z]=q
    z=z+1
  y=y+1
print(c)

[[10.  7. 10.]
 [ 7. 11.  6.]
 [15. 12. 11.]]


In [53]:
#ex5
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print("----------")
row=len(a)
y=-row
x=len(a[0])
g=0
z=0
while y<0:
  me=a[y].mean()
  while x>z :
    a[y,z]=a[y,z]-me
    z=z+1
  y=y+1
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------
[[-1  0  1]
 [ 4  5  6]
 [ 7  8  9]]
